// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpf6WzL_0UFzMf5BLZ5_XkmhP0hckI8ro',
    appId: '1:533039699998:web:efac61d7e4f5f8a5bc360f',
    messagingSenderId: '533039699998',
    projectId: 'truckpenny-1ad66',
    authDomain: 'truckpenny-1ad66.firebaseapp.com',
    storageBucket: 'truckpenny-1ad66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDYhPz9OwSBWkW_xMwDVo6hGEQxYWwBg',
    appId: '1:533039699998:android:51cdb08ce1e0dbddbc360f',
    messagingSenderId: '533039699998',
    projectId: 'truckpenny-1ad66',
    storageBucket: 'truckpenny-1ad66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhAN0sppfP_Iag7VsGktE0POvw76gx-kA',
    appId: '1:533039699998:ios:07381b8dd826a6efbc360f',
    messagingSenderId: '533039699998',
    projectId: 'truckpenny-1ad66',
    storageBucket: 'truckpenny-1ad66.appspot.com',
    iosBundleId: 'com.example.truckpenny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhAN0sppfP_Iag7VsGktE0POvw76gx-kA',
    appId: '1:533039699998:ios:b3b426434e9f6778bc360f',
    messagingSenderId: '533039699998',
    projectId: 'truckpenny-1ad66',
    storageBucket: 'truckpenny-1ad66.appspot.com',
    iosBundleId: 'com.example.truckpenny.RunnerTests',
  );
}
